import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { AuthProvider } from "@/context/AuthContext";

export const metadata = {
  title: "Mon Flux RSS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className="min-h-screen flex flex-col">
          <AuthProvider>
            <Header />
            <main className="flex-grow">{children}</main>
            <Footer className="mt-auto" />
          </AuthProvider>
      </body>
    </html>
  );
}
